### ISSUE TITLE
[Question]: ImportError: No module named interbotix_rpi_modules.neopixels

### ISSUE THREAD

**Issue by rcadit** [Interbotix/interbotix_ros_crawlers#3]
### Question

Hi, I was follwing the instructions at https://github.com/Interbotix/interbotix_ros_crawlers/issues/2#issuecomment-920217788 to install the software to simulate a wxmark4 on my laptop. 

I'm also having an error when launching this package. I am trying to walk_in_place.py, but get the following error:

`Traceback (most recent call last): File "move_in_place.py", line 3, in <module> from interbotix_xs_modules.hexapod import InterbotixHexapodXS File "/home/rcadit/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/hexapod.py", line 13, in <module> from interbotix_rpi_modules.neopixels import InterbotixRpiPixelInterface ImportError: No module named interbotix_rpi_modules.neopixels`

I followed the steps above to install the package for simulating, and also deleted my previous catkin_ws. Can you please help with this?

### Robot Model

wxmark4

### Operating System

Ubuntu 18.04

**Comment by rcadit** [comment]
I am also trying to run a gazebo simulation, but while the gazebo environment and simulation launches, running the example python files don't do anything in the simulation. Am I missing some node to launch?
